#.github/sync-Python-Actions.GoodInfo.Analyzer.yml
group:
  - files:
      # No. 50: Company info
      - source: raw_companyinfo.csv
        dest:   data/stage1_raw/raw_companyinfo.csv
    repos: |
        wenchiehlee-investment/Python-Actions.GoodInfo.Analyzer
